### ISSUE TITLE
Serving partials with django?

### ISSUE THREAD

**Issue by vincentalvo** [appliedsec/djangular#17]
Hi all,

I'm starting with djangular. I am trying to serve the partial files through Django instead of as static. 

This way, the HTML goes first through the Django engine and can be formated, translated, ... all the django goodness!

I can see it seems doable in django-angular
http://django-angular.readthedocs.org/en/latest/integration.html#partials

I got a weird error when I try to do it myself. The app.js seems not capable of loading the content... It looks like it is looping and and re-calls itself, thus resulting in a chrome crashing the page.

``` js
angular.module('sample', ['djangular','sample.filters', 'sample.services', 'sample.directives', 'sample.controllers','ngCookies']).
 config([
   '$routeProvider',
   'DjangoProperties',
   function($routeProvider, DjangoProperties) {
       $routeProvider.when('/view1', {templateUrl: '/sample/partials/subview/template', controller: 'MyCtrl1'});
       $routeProvider.when('/view2', {templateUrl: DjangoProperties.STATIC_URL + 'sample/partials/partial2.html', controller: 'MyCtrl2'});
       $routeProvider.otherwise({redirectTo: '/view1'});
 }]).
   run([
   '$http',
   '$cookies',
   function($http, $cookies) {
       $http.defaults.headers.post['X-CSRFToken'] = $cookies.csrftoken;
   }]);
```

view2 et working fine.
view1 does not load. Btw, I can load with no problem localhost:8000/sample/partials/subview/template

Any idea? 
Thanks a lot!

Vincent

**Comment by AncientSwordRage** [comment]
@vincentalvo did you ever put these in?

**Comment by vincentalvo** [comment]
Yes I did, but finally we gave up on angular all together, so it never really went to prod.
Definitely doable though.

**Comment by AncientSwordRage** [comment]
@vincentalvo  so these are in Djangular/master?

**Comment by vincentalvo** [comment]
No sorry, never put the PR together.

**Comment by AncientSwordRage** [comment]
@vincentalvo Give it a go? It sounds like a good pattern to follow.

**Comment by vincentalvo** [comment]
Yes it was good and robust. Unfortunately as I said I don't use angular anymore and I didn't keep this piece of code separated from my main project....

**Comment by AncientSwordRage** [comment]
@vincentalvo not to worry :+1:
