### ISSUE TITLE
Django 1.7 compatibility

### ISSUE THREAD

**Issue by stevejalim** [appliedsec/djangular#24]
`django.contrib.staticfiles.storage.AppStaticStorage` is no longer in Django as of 1.7[1], hence cannot be imported in `https://github.com/appliedsec/djangular/blob/master/djangular/storage.py`

[1] https://github.com/django/django/blob/stable/1.7.x/django/contrib/staticfiles/storage.py

**Comment by brian-montgomery** [comment]
A fix is now included in the django_17_compatibility branch and will soon be in the next official release.
