### ISSUE TITLE
django-1.7 startangularapp fails

### ISSUE THREAD

**Issue by qwiglydee** [appliedsec/djangular#33]
django.core.exceptions.ImproperlyConfigured: Command Command defines both "requires_model_validation" and "requires_system_checks", which is illegal. Use only "requires_system_checks".

pip freeze:
```
Django==1.7
-e git+git@github.com:appliedsec/djangular.git@9a128aec030ae27ea01a2fa0673839ce5ad1fa6a#egg=djangular-origin_django_17_compatibility
```

**Comment by brunosmartin** [comment]
Any news here?!

**Comment by qwiglydee** [comment]
Fixed in https://github.com/appliedsec/djangular/tree/django_17_compatibility
