### ISSUE TITLE
Question: is djangular going to survive the Angular2 transition?

### ISSUE THREAD

**Issue by web-snake** [appliedsec/djangular#34]
This is a question about the future of Djangular, not an issue with the current Djangular for Angular 1.x
I just wanted to ask if you have time or plans to work djangular around the new Angular2 framework.
I'm in the process of learning Angular2 so I can't off the top of my head figure out the implications of all the changes to Angular to what you're doing with Djangular, but I guess the project layout based on Angular Seed will be outdated. I can imagine this awesome project could evolve with the Angular2 transition, but I'm trying to plan a little into the future and wanted to see if you've got any plans to do that, and if so approximately when that might happen, or if, like many things I've come to love in Angular 1.x, it is going to find a new home in the graveyard.
( I couldn't figure out how to label this as a question, perhaps only you can do that? )

**Comment by itghisi** [comment]
Well, it seems that project is abandoned (no answers to the issues, no commits since the beginning of the year).

Is there any alternative to couple Angular with Django?
