### ISSUE TITLE
python manage.py startangularapp djangularTest does not work

### ISSUE THREAD

**Issue by Mohammad-hajiaghazadeh** [appliedsec/djangular#35]
hello
I want to use djangular in my django project but I have a problem. the problem is that when i want to create djangularapp in django project with this commant:
 ####### python manage.py startangularapp djangularTest ####### 
it shows me the below error:

------------------------------------------------------------------------------------------------------------------------
C:\Users\Mohammad\Desktop\andjango>python manage.py startangularapp djangularTes t Traceback (most recent call last):   File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)   File "C:\Python34\lib\site-packages\django\core\management\__init__.py", line 338, in execute_from_command_line
    utility.execute()   File "C:\Python34\lib\site-packages\django\core\management\__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)   File "C:\Python34\lib\site-packages\django\core\management\base.py", line 390,  in run_from_argv
    self.execute(*args, **cmd_options)   File "C:\Python34\lib\site-packages\django\core\management\base.py", line 441,  in execute
    output = self.handle(*args, **options)   File "C:\Python34\lib\site-packages\djangular-0.3.0b1-py3.4.egg\djangular\mana gement\commands\startangularapp.py", line 20, in handle
    mgmt.call_command('startapp', app_name, target, **options) 
TypeError: call_command() got multiple values for argument 'name'
------------------------------------------------------------------------------------------------------------------------
i've tried to use multiple values but it does not work?
can anyone help me?
regards.

**Comment by nicholasserra** [comment]
This is now fixed, thanks!
