### ISSUE TITLE
Project no longer maintained?

### ISSUE THREAD

**Issue by nicholasserra** [appliedsec/djangular#42]
@EliAndrewC hello, wondering if this project is no longer maintained? I'd like to use this for a Django 1.9 project. Do you need assistance in keeping it up to date? Let me know. I'd be interested in becoming a maintainer, or taking control of the project. Thanks!

**Comment by Huuuze** [comment]
It's still being maintained. Unfortunately, we've been focused on other initiatives.

**Comment by EliAndrewC** [comment]
@nicholasserra I've spoken further with the team, and we agreed that that's unlikely that we'll be given time to keep Djangular up to date in the forseeable future.  We'd therefore appreciate any help you're willing to offer.  Thanks so much for reaching out on this!

How does this sound:
- You can make a Pull Request with some updates that either implement Django 1.9 compatibility or at least get us closer to it.
- The team reviews it, and after it's accepted we bump you up to being one of the maintainers on this repo.
- After that we'll keep an eye on whatever you're able to do with the project to offer feedback / suggestions.
- In the long run, if we end up finding that we just don't have any time we might just turn the project completely over to you.

Does that seem like a reasonable way forward?  Thanks again for offering to help out!

**Comment by nicholasserra** [comment]
@EliAndrewC Sounds good, i'll probably do some work on it this weekend, thanks!

**Comment by nicholasserra** [comment]
@EliAndrewC Could you log into Travis CI at https://travis-ci.org/ and enable this repository? I'd like to get multi django version testing running. Thanks!

**Comment by Huuuze** [comment]
@nicholasserra You're all set on Travis CI.
